#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  cd "$shome"

  block compile pipenv
  block compile yarn
  mkdir -p "$shome/bin"
  ln -nfs $(pipenv run which chalice http http-prompt) "$shome/bin/"
  ln -nfs $(yarn exec -s which sam claudia) "$shome/bin/"
}

main "$@"
