#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  cd "$shome"

  block compile pipenv
  block compile yarn
  mkdir -p "$shome/bin"
  ln -nfs $(pipenv run which http http-prompt sam) "$shome/bin/"
  ln -nfs $(yarn exec -s which lambci) "$shome/bin/"
}

main "$@"
