#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  test -z "$(check | cat)"
}

function check {
  if [[ "$($shome/script/version | jq -r '.httpie')" != "$HTTPIE_VERSION" ]]; then
    echo 1
  fi &

  if [[ "$($shome/script/version | jq -r '.http_prompt')" != "$HTTP_PROMPT_VERSION" ]]; then
    echo 1
  fi &

  if ! type -P lambci >/dev/null; then
    echo 1
  fi &
}

main "$@"
