#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  if [[ "$($shome/script/version | jq -r '.httpie')" != "$HTTPIE_VERSION" ]]; then
    return 1
  fi

  if [[ "$($shome/script/version | jq -r '.http_prompt')" != "$HTTP_PROMPT_VERSION" ]]; then
    return 1
  fi

  if ! type -P lambci 2>/dev/null; then
    return 1
  fi

  return 0
}

main "$@"
