#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_lambda="0.0.1"
  jq -n --arg lambda "$ver_lambda" '{lambda: $lambda}'
}

version "$@"
