#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_httpie="$(http --version 2>/dev/null || true)"
  local ver_http_prompt="$(http-prompt --version 2>/dev/null || true)"
  jq -n --arg httpie "$ver_httpie" --arg http_prompt "$ver_http_prompt" \
    '{httpie: $httpie, http_prompt: $http_prompt}'
}

version "$@"
